version: '3.9'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: pgdev
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
  rtmp:
    image: longridgehighschool/nginx-rtmp-ssl:main
    restart: always
    environment:
      SERVER_NAME: rtmp.dev
      RTMP_PUBLISH_URLS: http://host.docker.internal:3000/live/api/play
      RTMP_DONE_URLS: http://host.docker.internal:3000/live/api/done
    volumes:
      - ./data/ssl:/var/ssl
    ports:
      - '1935:1935'
      - '8443:443'
